exclude: ^data/
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
    - id: isort
      name: isort (python)
- repo: https://github.com/psf/black
  rev: 23.9.1
  hooks:
    - id: black
      language_version: python3.11
- repo: https://github.com/python-poetry/poetry
  rev: 1.6.0
  hooks:
    - id: poetry-check
    - id: poetry-lock
    - id: poetry-export
- repo: local
  hooks:
    - id: pylint
      name: pylint
      entry: pylint
      language: system
      types: [python]
      args: [
        "-rn", # Only display messages
        "-sn", # Don't display the score
        "--recursive=y"
        ]
